# Generated by Django 5.2.5 on 2025-09-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_gxp_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='password_require_capital',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='password_require_number',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='password_require_small',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='password_require_special',
        ),
    ]
