# Generated by Django 5.2.5 on 2025-09-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_systemsettings_password_require_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
