# Generated by Django 5.0.6 on 2025-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_admin_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_id',
            field=models.CharField(max_length=255),
        ),
    ]
